# Generated by Django 2.2.5 on 2020-06-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='answer',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
