# Generated by Django 2.2.5 on 2020-06-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20200626_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['course']},
        ),
        migrations.AlterField(
            model_name='application',
            name='Status',
            field=models.CharField(blank=True, default='Waiting for apply', max_length=255, null=True),
        ),
    ]
