# Generated by Django 2.2.5 on 2020-06-27 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20200626_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_applications', to='course.Course'),
        ),
    ]
