# Generated by Django 2.2.5 on 2020-06-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20200627_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='answer',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
