# Generated by Django 2.2.5 on 2020-06-27 17:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20200627_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['Apply_Date']},
        ),
        migrations.AlterField(
            model_name='application',
            name='Apply_Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 17, 40, 19, 123111, tzinfo=utc), max_length=255),
        ),
    ]
