# Generated by Django 2.2.5 on 2020-06-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('session_no', models.CharField(max_length=255)),
                ('content_session', models.CharField(max_length=255)),
                ('Price', models.IntegerField(max_length=255)),
                ('Status', models.CharField(max_length=255)),
            ],
        ),
    ]
