# Generated by Django 2.2.5 on 2020-06-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
