# Generated by Django 2.2.5 on 2020-06-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200624_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='session_no',
            new_name='session_number',
        ),
        migrations.AlterField(
            model_name='course',
            name='Description',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='course',
            name='content_session',
            field=models.TextField(max_length=3000),
        ),
    ]
