# Generated by Django 2.2.5 on 2020-06-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200624_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Price',
            field=models.IntegerField(blank=True),
        ),
    ]
