# Generated by Django 2.2.5 on 2020-06-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200624_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='Status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
