# Generated by Django 2.2.5 on 2020-06-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20200624_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='Status',
            field=models.CharField(max_length=255),
        ),
    ]
