# Generated by Django 2.2.5 on 2020-06-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20200624_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Image',
            field=models.URLField(blank=True, default='https://prod-discovery.edx-cdn.org/media/course/image/9a59c035-7000-49c4-9e38-b490e204657f-6abf8ade4c33.small.png'),
        ),
    ]
