# Generated by Django 2.2.5 on 2020-06-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20200624_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
