# Generated by Django 2.2.5 on 2020-06-25 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20200625_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='session_number',
            new_name='Number_of_Session',
        ),
    ]
