# Generated by Django 2.2.5 on 2020-06-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20200625_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Number_of_Session',
            new_name='Number_of_Sessions',
        ),
    ]
