# Generated by Django 2.2.5 on 2020-06-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_auto_20200625_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Start_date',
            field=models.DateField(),
        ),
    ]
