# Generated by Django 2.2.5 on 2020-06-25 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20200625_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='content_session',
            new_name='Course_Content',
        ),
    ]
