# Generated by Django 2.2.5 on 2020-06-25 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
        ('course', '0017_auto_20200625_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Trainer',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='trainer.Trainer'),
            preserve_default=False,
        ),
    ]
