# Generated by Django 2.2.5 on 2020-06-25 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_course_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Trainer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='trainer.Trainer'),
        ),
    ]
