# Generated by Django 2.2.5 on 2020-06-25 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_auto_20200625_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='trainer.Trainer'),
        ),
    ]
