# Generated by Django 2.2.5 on 2020-06-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_auto_20200625_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
