# Generated by Django 2.2.5 on 2020-06-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_auto_20200625_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Start_date',
            field=models.DateField(blank=True, default='null', null=True),
        ),
    ]
