# Generated by Django 2.2.5 on 2020-06-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_auto_20200625_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='Start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
