# Generated by Django 2.2.5 on 2020-06-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_auto_20200625_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isbn_number', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
            ],
        ),
    ]
