# Generated by Django 2.2.5 on 2020-06-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0025_book_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='questions',
        ),
        migrations.AlterModelTable(
            name='book',
            table=None,
        ),
    ]
