# Generated by Django 2.2.5 on 2020-06-26 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0027_auto_20200626_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='answer',
        ),
    ]
