# Generated by Django 2.2.5 on 2020-06-28 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0028_remove_questionanswer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='trainer.Trainer'),
        ),
    ]
