# Generated by Django 2.2.5 on 2020-06-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='123', max_length=255)),
                ('Title', models.CharField(default='123', max_length=255)),
                ('Facebook_URL', models.URLField(default='https://www.abprojeyonetimi.com/wp-content/uploads/2019/09/online-course-development-process-must-know-outsource.jpeg')),
                ('Instagram_URL', models.URLField(default='https://www.abprojeyonetimi.com/wp-content/uploads/2019/09/online-course-development-process-must-know-outsource.jpeg')),
                ('Whatsapp_Number', models.CharField(default='123', max_length=255)),
                ('Linkedin_URL', models.URLField(default='https://www.abprojeyonetimi.com/wp-content/uploads/2019/09/online-course-development-process-must-know-outsource.jpeg')),
                ('Image_URL', models.URLField(default='https://www.abprojeyonetimi.com/wp-content/uploads/2019/09/online-course-development-process-must-know-outsource.jpeg')),
            ],
        ),
    ]
