# Generated by Django 2.2.5 on 2020-06-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='Facebook_URL',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Instagram_URL',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Linkedin_URL',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Whatsapp_Number',
            field=models.CharField(max_length=255),
        ),
    ]
