# Generated by Django 2.2.5 on 2020-06-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='remember_me',
            field=models.BooleanField(default=False),
        ),
    ]
