# Generated by Django 2.2.5 on 2020-06-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_remember_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='remember_me',
        ),
    ]
